language: c
dist: xenial
sudo: required
cache:
  directories:
    - $HOME/qemu
addons:
  apt:
    update: true
    packages:
    - parted
    - wget
    - dosfstools
    - zip
    - systemd-container
before_script:
  - echo "deb http://ftp.debian.org/debian jessie-backports main\ndeb-src http://ftp.debian.org/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get build-dep qemu
  - export QEMU_ARCHES="aarch64"
  - git clone https://github.com/julianxhokaxhiu/qemu.git qemu
  - cd qemu 
  - git checkout execve-2.9 
  - ./configure --disable-bsd-user --disable-guest-agent --disable-strip --disable-werror --disable-gcrypt --disable-debug-info --disable-debug-tcg --enable-docs --disable-tcg-interpreter --enable-attr --disable-brlapi --disable-linux-aio --disable-bzip2 --disable-bluez --disable-cap-ng --disable-curl --disable-fdt --disable-glusterfs --disable-gnutls --disable-nettle --disable-gtk --disable-rdma --disable-libiscsi --disable-vnc-jpeg --disable-kvm --disable-lzo --disable-curses --disable-libnfs --disable-numa --disable-opengl --disable-vnc-png --disable-rbd --disable-vnc-sasl --disable-sdl --disable-seccomp --disable-smartcard --disable-snappy --disable-spice --disable-libssh2 --disable-libusb --disable-usb-redir --disable-vde --disable-vhost-net --disable-virglrenderer --disable-virtfs --disable-vnc --disable-vte --disable-xen --disable-xen-pci-passthrough --disable-xfsctl --enable-linux-user --disable-system --disable-blobs --disable-tools --target-list=arm-linux-user --static --disable-pie
  - make -j 2
  - make install
  - export PATH=$PATH:$PWD/qemu/bin
script:
  - ls -R qemu/
  - sudo ./build_image.sh
deploy:
  provider: releases
  api_key:
    secure: csd25m7/7gpVZTuA810jxjIuGDtpd91dtCvYlRstZp0AROfYcIfSwNaXEQ5EB4cpWMtXAxWpIgCzXmjr8swzwy6KWgxOgrhcRPqPjyNcOhM9/gDs6hxS70Lnj9QIlPexVQ0dKQRXABBvzcU5XmFrtEoMlelQt2vBeSL+HHNcX6dyzUkJk5W9NemUp31G3anwMD1Oxv/+WMcew97uqDnoZwqZlm5oDQfiwhK+jApfv3NYrTuhL2wFUv3Ab7f6+JZBcw7cBDS3CHWLZWSG79yocSkcznMA9gEU9qKtcNoaIYG+ZgpCOW8daY7JSmj+k27ltCLIWA11sIeiSfMnrgsE7vBSpl5yubTYCn9ON9EKVxJuUA37FMiEfJJAkOn75ei2R5df2YnNRscWaBinPZKGIgXtS/xOUbmJDHDsArpYGilxNA/ZNhr48IiPOWRH+ds4QPndbw47RRSE2IALCUraHG329ZcSuZTvVulA2lL4VfRFf49LDnTxBmZSqwspzq2jjBXMzXX4/f0w+o0EVPEIQw2szpgM12i+kkgtKmDcTRSt+OMNARIvEmsLCbILGJz9z4xhqESiZdjac9xMOx+lb5oGDMW/0F9EopeKT2eqkpRj6bZUK84uLNsdoBMpsE4BctIkTlDMGtL0hIqVaU7RerT7Hu7aXw/cLyDjI44Z3uQ=
  file: sopine_arch_headless.img.xz
  skip_cleanup: true
  on:
    repo: jeanlego/linux-build
    branch: mainline